### ISSUE TITLE
Console commands doesn't autoload classes

### ISSUE THREAD

**Issue by x-yuri** [yiisoft/yii#3904]
I'm running `yii-1.1.14`. And I'm trying to create console command, but when I run it, it says:

```
PHP Error[2]: include(Model.php): failed to open stream: No such file or directory
    in file /srv/http/bg/framework/YiiBase.php at line 427
#0 /srv/http/bg/framework/YiiBase.php(427): autoload()
#1 unknown(0): autoload()
#2 /srv/http/bg/protected/commands/C1Command.php(19): spl_autoload_call()
#3 /srv/http/bg/framework/console/CConsoleCommandRunner.php(71): C1Command->run()
#4 /srv/http/bg/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run()
#5 /srv/http/bg/framework/base/CApplication.php(180): CConsoleApplication->processRequest()
#6 /srv/http/bg/framework/yiic.php(33): CConsoleApplication->run()
#7 /srv/http/bg/protected/yiic.php(7): require_once()
#8 /srv/http/bg/protected/yiic(4): require_once()
```

I saw [this other issue][1], and [this `stackoverflow question][2], but it doesn't help me. Adding

```
    'components' => array(
        ...
        'import' => array(                                                                                             
            'application.models.*',                                                                                    
        ),
    ),
```

to config makes no difference.

[1]: https://github.com/yiisoft/yii/issues/2344
[2]: http://stackoverflow.com/questions/25428526/console-app-in-yii-fails-to-include-ar-model

**Comment by cebe** [comment]
import is a property of the application so it has to be outside of 'components'. please use the forum to ask further questions, github is for bug tracking.
