### ISSUE TITLE
ConsoleCommand and its behaviors do not have a method or closure named "createUrl"

### ISSUE THREAD

**Issue by x-yuri** [yiisoft/yii#3905]
I'm trying to createUrl() from console command:

```
exception 'CException' with message 'C1Command and its behaviors do not have a method or closure named "createUrl".' in /srv/http/bg/framework/base/CComponent.php:266
Stack trace:
#0 /srv/http/bg/protected/commands/C1Command.php(22): CComponent->__call('createUrl', Array)
#1 /srv/http/bg/protected/commands/C1Command.php(22): C1Command->createUrl('hotels/view/inf...', Array)
#2 /srv/http/bg/framework/console/CConsoleCommandRunner.php(71): C1Command->run(Array)
#3 /srv/http/bg/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#4 /srv/http/bg/framework/base/CApplication.php(180): CConsoleApplication->processRequest()
#5 /srv/http/bg/framework/yiic.php(33): CApplication->run()
#6 /srv/http/bg/protected/yiic.php(7): require_once('/srv/http/bg/fr...')
#7 /srv/http/bg/protected/yiic(4): require_once('/srv/http/bg/pr...')
#8 {main}
```

I'm running `yii-1.1.14`. How should I go about it?

**Comment by cebe** [comment]
the console has no information about the web application, you have to configure a request component in the application and configure its properties. then you can call `Yii::app()->urlManager->createUrl(...);`
