### ISSUE TITLE
quoteValue don't escape backslash (SQL injection in batchInsert?)

### ISSUE THREAD

**Issue by Dador** [yiisoft/yii#3920]
Test code:
```
 $rows = [['id' => 1, 'name' => 'test\\'], ['id' => 2, 'name' => ':test'], ['id' => 3, 'name' => '?']];
 $command = Yii::$app->db->createCommand()->batchInsert(Groups::tableName(), ['id', 'name'], $rows);
 $command->execute();
```

Generated SQL: (notice that \ is unescaped).
```
INSERT INTO "groups" ("id", "name") VALUES (1, 'test\'), (2, ':test'), (3, '?')
```

Exception:
```
Exception 'yii\db\Exception' with message 'SQLSTATE[HY093]: Invalid parameter number: mixed named and positional parameters
Failed to prepare SQL: INSERT INTO "groups" ("id", "name") VALUES (1, 'test\'), (2, ':test'), (3, '?')'

in \vendor\yiisoft\yii2\db\Command.php:227

Error Info:
Array
(
    [0] => HY093
    [1] => 0
)

Stack trace:
#0 \vendor\yiisoft\yii2\db\Command.php(775): yii\db\Command->prepare(false)
#1 \SomeController.php(58): yii\db\Command->execute()
#2 [internal function]: app\commands\SomeController->actionSome()
#3 \vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#4 \vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#5 \vendor\yiisoft\yii2\console\Controller.php(91): yii\base\Controller->runAction('some', Array)
#6 \vendor\yiisoft\yii2\base\Module.php(455): yii\console\Controller->runAction('some', Array)
#7 \vendor\yiisoft\yii2\console\Application.php(167): yii\base\Module->runAction('some/some', Array)
#8 \vendor\yiisoft\yii2\console\Application.php(143): yii\console\Application->runAction('some/some', Array)
#9 \vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#10 \htdocs\midito\yii(19): yii\base\Application->run()
#11 {main}
```

Database: PostgreSQL (I didn't tested on MySQL so I'm not sure that it matters)

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2/issues/6526
