### ISSUE TITLE
CActiveRecord class Error (using Mssql) Query Functions Result in Error in the INFORMATION_SCHEMA Table

### ISSUE THREAD

**Issue by aireol** [yiisoft/yii#3926]
Hi!

I am trying to write a child class of the `CActiveRecord` class, but results in an error below in the `INFORMATION_SCHEMA` table: 

_My environment:_
MSSQL Server 11.0.3153
pdo_sqlsrv driver
PHP 5.4
Yii 1.1.16
IIS
ZendServer 7

Here's my implementation:

```
<?php
class User extends CActiveRecord
{
    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }

    public function tableName(){
        return '[my_database].[dbo].[user]';
    }

    // public function getDbConnection(){}
}
```

My usage:

```
<?php 
...
$instance = User::model()->findByPk(19086);
print_r($instance);
...
```

Error log:

```

2015/08/20 10:54:46 [trace] [system.db.CDbCommand] Querying SQL:        SELECT k.column_name field_name
        FROM [my_database].[INFORMATION_SCHEMA].[KEY_COLUMN_USAGE] k
        LEFT JOIN [my_database].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] c
        ON k.table_name = c.table_name
            AND k.constraint_name = c.constraint_name
        WHERE c.constraint_type ='PRIMARY KEY'
            AND k.table_name = :table
            AND k.table_schema = :schema. Bound with :table='user', :schema='dbo'
in C:\inetpub\wwwroot\gps_listener\trunk\protected\commands\DTDMemberUploadCommand.php (93)
in C:\inetpub\wwwroot\gps_listener\trunk\console.php (35)

2015/08/20 10:54:46 [trace] [system.CModule] Loading "coreMessages" application component
in C:\inetpub\wwwroot\gps_listener\trunk\protected\commands\DTDMemberUploadCommand.php (93)
in C:\inetpub\wwwroot\gps_listener\trunk\console.php (35)

2015/08/20 10:54:46 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: 
SQLSTATE[42S02]: [Microsoft][SQL Server Native Client 11.0][SQL Server] Invalid object name 'my_database.INFORMATION_SCHEMA.KEY_COLUMN_USAGE'.. The SQL statement executed was:
        SELECT k.column_name field_name
        FROM [my_database].[INFORMATION_SCHEMA].[KEY_COLUMN_USAGE] k
        LEFT JOIN [my_database].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] c
        ON k.table_name = c.table_name
            AND k.constraint_name = c.constraint_name
        WHERE c.constraint_type ='PRIMARY KEY'
            AND k.table_name = :table
            AND k.table_schema = :schema. Bound with :table='user', :schema='dbo'.
in C:\inetpub\wwwroot\gps_listener\trunk\protected\commands\DTDMemberUploadCommand.php (93)
in C:\inetpub\wwwroot\gps_listener\trunk\console.php (35)

2015/08/20 10:54:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid object name 'my_database.INFORMATION_SCHEMA.KEY_COLUMN_USAGE'.. The SQL statement executed was:      SELECT k.column_name field_name
        FROM [my_database].[INFORMATION_SCHEMA].[KEY_COLUMN_USAGE] k
        LEFT JOIN [my_database].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] c
        ON k.table_name = c.table_name
            AND k.constraint_name = c.constraint_name
        WHERE c.constraint_type ='PRIMARY KEY'
            AND k.table_name = :table
            AND k.table_schema = :schema. Bound with :table='user', :schema='dbo'' in C:\inetpub\wwwroot\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\inetpub\wwwroot\yii\framework\db\CDbCommand.php(455): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\inetpub\wwwroot\yii\framework\db\schema\mssql\CMssqlSchema.php(210): CDbCommand->queryColumn()
#2 C:\inetpub\wwwroot\yii\framework\db\schema\mssql\CMssqlSchema.php(139): CMssqlSchema->findPrimaryKey(Object(CMssqlTableSchema))
#3 C:\inetpub\wwwroot\yii\framework\db\schema\CDbSchema.php(103): CMssqlSchema->loadTable('[my_database].[d...')
#4 C:\inetpub\wwwroot\yii\framework\db\ar\CActiveRecord.php(2384): CDbSchema->getTable('[my_database].[d...')
#5 C:\inetpub\wwwroot\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#6 C:\inetpub\wwwroot\yii\framework\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#7 C:\inetpub\wwwroot\yii\framework\db\ar\CActiveRecord.php(1490): CActiveRecord->getTableSchema()
#8 C:\inetpub\wwwroot\gps_listener\trunk\protected\commands\DTDMemberUploadCommand.php(93): CActiveRecord->findByPk(19086)
#9 [internal function]: DTDMemberUploadCommand->actionTest()
#10 C:\inetpub\wwwroot\yii\framework\console\CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(DTDMemberUploadCommand), Array)
#11 C:\inetpub\wwwroot\yii\framework\console\CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#12 C:\inetpub\wwwroot\yii\framework\console\CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#13 C:\inetpub\wwwroot\yii\framework\base\CApplication.php(184): CConsoleApplication->processRequest()
#14 C:\inetpub\wwwroot\gps_listener\trunk\console.php(35): CApplication->run()
#15 {main}

---
2015/08/20 10:54:46 [trace] [system.CModule] Loading "errorHandler" application component
2015/08/20 10:54:46 [trace] [system.CModule] Loading "request" application component

```

**Comment by aireol** [comment]
I tried to run this query but did not resulted in the error `Invalid object name 'my_database.INFORMATION_SCHEMA.KEY_COLUMN_USAGE'`:

````
SELECT k.column_name field_name
		FROM [my_database].[INFORMATION_SCHEMA].[KEY_COLUMN_USAGE] k
		LEFT JOIN [my_database].[INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] c
		ON k.table_name = c.table_name
			AND k.constraint_name = c.constraint_name
		WHERE c.constraint_type ='PRIMARY KEY'
			AND k.table_name = 'user'
			AND k.table_schema = 'dbo'
````

**Comment by jjdunn** [comment]
works fine in SQL Server 2008 R2, which we've been using with Yii since 2010.
