### ISSUE TITLE
CUrlManager rule unexpectedly breaks if matching parameter has only one character

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#4041]
I have this configuration in `config/main.php` for the `urlManager` component:
```
'urlManager'=>array(
	'urlFormat'=>'path',
	'showScriptName'=>false,
	'appendParams'=>false,
	'rules'=>array(
		'about'=>'site/about',	
		'info/<page:\w+>'=>'site/page/view/info.<page>',
		'support/tutorial'=>'site/page/view/support.tutorial',
		'terms'=>'site/page/view/terms',
		'credits'=>'site/page/view/credits',
		'projector/~<areas:[^\d].*>'=>'projector/view',
		'<controller:\w+>/<id:\d+>'=>'<controller>/view',
		'<controller:\w+>/<action:\w+>/<id:\d+>'=>'<controller>/<action>',
		'\*<author_id:\w[^\/]+>'=>'message/index',
		'<controller:\w+>/<action:\w+>'=>'<controller>/<action>',
		'feedback'=>'site/feedback',
		'contact'=>'site/contact',
		'post'=>'message/publish',
		
		
	),
),
```

the relevant rule for the issue being:
```
		'\*<author_id:\w[^\/]+>'=>'message/index',
```

So, an url like
```
http://mydomain.com/*foo
```
is "mapped" to 
```
/message/index?author_id=foo
```

This works as expected as long as the `author_id` token has at least two characters.

However, if it has only one character, such as:
```
http://mydomain.com/*m
```
it triggers a 400 error:

```
exception 'CHttpException' with message 'Unable to resolve the request "*m".' in /srv/www/xxx/public_html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /srv/www/xxx/public_html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('*m')
#1 /srv/www/xxx/public_html/yii/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /srv/www/xxx/public_html/index.php(27): CApplication->run()
#3 {main}
```

**Comment by tomtomsen** [comment]
Your rule ` '\*<author_id:\w[^\/]+>'` expects a star, followed by an author_id which has a word character [a-zA-Z0-9_] **and**  at least one character expect /. 

try replacing the plus (+) character with a star (*).
or just use  `author_id:\w+`
