### ISSUE TITLE
PHP 7.1.14 CHtml.php error

### ISSUE THREAD

**Issue by hitman249** [yiisoft/yii#4193]
```
2018/02/08 04:39:37 [error] [exception.Error] Error: Cannot unset string offsets in /var/www/framework/web/helpers/CHtml.php:2578
Stack trace:
#0 /var/www/framework/web/helpers/CHtml.php(1995): CHtml::listOptions(0, Array, 'G')
#1 /var/www/framework/web/widgets/CActiveForm.php(914): CHtml::activeDropDownList(Object(Gateways), 'country_id', Array, 'G')
#2 /var/www/protected/helpers/GUI.php(1039): CActiveForm->dropDownList(Object(Gateways), 'country_id', Array, 'f')
...
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.19 (stable)
| PHP version      | 7.1.14
| Operating system | Docker ( laradock.io )

**Comment by samdark** [comment]
Seems you've set htmlOptions to string.
